FROM nginx:alpine

WORKDIR /var/www/html

# Copiamo la cartella public dentro il container Nginx
COPY public /var/www/html/public

# Copiamo la configurazione
COPY docker/nginx/default.conf /etc/nginx/conf.d/default.conf